types:
  major: "Major: Breaking Changes"
  minor: "Minor: Backward Compatible Changes"
  patch: "Patch: Bug Fixes"
scopes:
  feat:
    [
      build,
      developer experience,
      application code,
      ci/cd,
      tests,
      docs,
      monitoring,
    ]
  fix:
    [
      build,
      developer experience,
      application code,
      ci/cd,
      tests,
      docs,
      monitoring,
    ]
  chore:
    [
      build,
      developer experience,
      application code,
      ci/cd,
      tests,
      docs,
      monitoring,
    ]
