#!/usr/bin/env bash

# This script is based on code from https://github.com/pulumi/pulumi
# Copyright 2023 karmingc
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0

set -euo pipefail

ROOT=$(dirname "${0}")/../..

if [ -n "${CI:-""}" ]; then
  >&2 echo "::group::Get version"
  trap ">&2 echo '::endgroup::'" EXIT # bash equivalent of defer func()
fi

# Remove whitespace, this is our version:
tr -d '[:space:]' < "${ROOT}/.version"
