name: On PR

on:
  pull_request:
    paths-ignore:
      - ".version"

jobs:
  changelog-comment:
    name: Changelog comment
    uses: ./.github/workflows/changelog-comment.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      base-ref: origin/${{ github.base_ref }}
      pr-number: ${{ github.event.pull_request.number }}
      skip: ${{ startsWith(github.head_ref, 'release/') }}
    secrets: inherit

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  get-cl-entries:
    name: Get changelog entries
    runs-on: ubuntu-latest
    outputs:
      entries: ${{ steps.get-number-of-entries.outputs.entries }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get number of entries
        run: |
          number=$(ls -1 ./changelog/pending | wc -l)
          echo "entries=${number}" >> $GITHUB_OUTPUT
  bump-version-pr:
    name: Bump version PR
    needs: [get-cl-entries]
    runs-on: ubuntu-latest
    if: ${{ needs.get-cl-entries.outputs.entries >= 3 }}
    steps:
      - name: echo something
        run: |
          echo "${{ needs.get-cl-entries.outputs.entries }}"
